# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ local-mode ]
  pull_request:
    branches: [ local-mode ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
     - uses: actions/checkout@v1
     - name: Setup node
       uses: actions/setup-node@v2
       with:
          node-version: '16.x'
     - run: |
          npm install
          npm run dist
     - uses: "marvinpinto/action-automatic-releases@latest"
       with:
          repo_token: "${{ secrets.ACCESS_TOKEN }}"
          automatic_release_tag: "${{matrix.os}}-latest"
          prerelease: false
          title: "Unit List"
          files: |
            dist/*
